### ISSUE TITLE
AttributeError: 'module' object has no attribute 'sub'

### ISSUE THREAD

**Issue by maria-ito** [linjian93/tensorflow_homographynet#3]
Hi,

I managed to prepare the data, however I am getting this error when I attempt training. Does anyone have an idea of why this is happening? 

Cheers

python train_mycnn.py 
Traceback (most recent call last):
  File "train_mycnn.py", line 320, in <module>
    tf.app.run()
  File "/home/maria/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "train_mycnn.py", line 269, in main
    loss = tf.reduce_sum(tf.square(tf.sub(fc2, x2))) / 2 / batch_size
AttributeError: 'module' object has no attribute 'sub'

**Comment by maria-ito** [comment]
I found out that the tf.sub command is deprecated, and replaced it by tf.subtract
